# Generated by Django 6.0.7 on 2026-07-24 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('nationality', models.CharField(choices=[('OM', 'Oman'), ('IN', 'India'), ('PK', 'Pakistan'), ('BD', 'Bangladesh'), ('PH', 'Philippines'), ('NP', 'Nepal'), ('EG', 'Egypt'), ('OTH', 'Other')], max_length=10)),
                ('passport_number', models.CharField(blank=True, max_length=100, null=True)),
                ('join_date', models.DateField()),
                ('designation', models.CharField(blank=True, max_length=150, null=True)),
                ('department', models.CharField(blank=True, max_length=150, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='companies.company')),
            ],
            options={
                'unique_together': {('company', 'employee_code')},
            },
        ),
    ]
