# Generated by Django 6.0.7 on 2026-07-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='passport_number',
            new_name='position',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='join_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nationality',
            field=models.CharField(choices=[('OM', 'Omani'), ('IN', 'Indian'), ('PK', 'Pakistani'), ('BD', 'Bangladeshi'), ('NP', 'Nepali'), ('PH', 'Filipino'), ('EG', 'Egyptian'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
