# Generated by Django 6.0.7 on 2026-07-26 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('documents', '0003_alter_document_employee_alter_document_title'),
        ('employees', '0003_alter_employee_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AlterField(
            model_name='document',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
