# Generated by Django 6.0.7 on 2026-07-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_alter_payroll_net_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
