# Generated by Django 6.0.7 on 2026-07-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_payroll_bonus_payroll_incentives'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payroll',
            old_name='created_at',
            new_name='generated_at',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='allowances',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='overtime_pay',
        ),
        migrations.AddField(
            model_name='payroll',
            name='allowance',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='final_pay',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payroll',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='net_salary',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
