# Generated by Django 6.0.7 on 2026-07-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_rename_created_at_payroll_generated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='month',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='year',
        ),
        migrations.AddField(
            model_name='payroll',
            name='date',
            field=models.DateField(default='2026-01-01'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='gross_salary',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
