# Generated by Django 6.0.7 on 2026-07-26 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_alter_payroll_allowance_alter_payroll_basic_salary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='final_pay',
        ),
    ]
