# Generated by Django 6.0.7 on 2026-07-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_remove_payroll_final_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='allowance',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='basic_salary',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
