# Generated by Django 6.0.7 on 2026-07-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_alter_payroll_allowance_alter_payroll_basic_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='allowance',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='basic_salary',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=10),
        ),
    ]
