# Generated by Django 6.0.7 on 2026-07-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_rename_remarks_attendance_remark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('half_day', 'Half Day'), ('leave', 'Leave'), ('medical_leave', 'Medical Leave'), ('earned_leave', 'Earned Leave'), ('casual_leave', 'Casual Leave'), ('unpaid_leave', 'Unpaid Leave'), ('holiday', 'Holiday'), ('weekoff', 'Week Off'), ('work_from_home', 'Work From Home'), ('travel', 'Travel'), ('training', 'Training'), ('duty_leave', 'Duty Leave')], default='present', max_length=30),
        ),
    ]
