# Generated by Django 6.0.7 on 2026-07-26 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_status'),
        ('companies', '0001_initial'),
        ('employees', '0004_employee_allowance_employee_basic_salary_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('half_day', 'Half Day'), ('leave', 'Leave'), ('medical_leave', 'Medical Leave'), ('earned_leave', 'Earned Leave'), ('casual_leave', 'Casual Leave'), ('unpaid_leave', 'Unpaid Leave'), ('holiday', 'Holiday'), ('weekoff', 'Week Off'), ('work_from_home', 'Work From Home'), ('travel', 'Travel'), ('training', 'Training'), ('duty_leave', 'Duty Leave')], max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('company', 'employee', 'date')},
        ),
        migrations.CreateModel(
            name='Overtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('day_type', models.CharField(choices=[('working_day', 'Working Day'), ('holiday', 'Holiday')], max_length=20)),
                ('rate_per_hour', models.DecimalField(decimal_places=3, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('paid', models.BooleanField(default=False)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtimes', to='companies.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtimes', to='employees.employee')),
            ],
            options={
                'ordering': ['-work_date', '-id'],
                'unique_together': {('company', 'employee', 'work_date')},
            },
        ),
    ]
