# Generated by Django 6.0.7 on 2026-07-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_attendance_options_alter_attendance_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtime',
            name='amount',
            field=models.DecimalField(decimal_places=3, editable=False, max_digits=10),
        ),
    ]
